version: '3'

services:
  frontend:
    build:
        context: .
        dockerfile: Dockerfile.Development
    command: nginx -g 'daemon off;'
    volumes:
      - .:/app
    ports:
      - "80:80"
      - "443:443"