version: '3'

services:
  backend:
    build:
      context: ./python-env/
      dockerfile: ./backend/Dockerfile
    ports:
      - "3001:80"

  frontend:
    build:
      context: ./frontend/
      args:
        BACKEND_URL: ${REACT_APP_API_URL}
    ports:
      - "80:80"
      - "443:443"