version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.Development
    command: sh -c "python api.py & nginx -g 'daemon off;'"
    environment:
        - FLASK_DEBUG=1
    volumes:
      - .:/app
    ports:
      - "8080:80"
      - "4433:443"