name: Static Analysis Python API

on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'backend/*'
      - 'python/scripts/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run static analysis
        run: |
          pip install sonar-scanner
          sonar-scanner -Dsonar.projectBaseDir=./backend,./python/scripts -Dsonar.projectKey=parodontitis-api
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_API }}
