name: Static Analysis React Web

on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'frontend/*'

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Change to frontend directory
        run: cd frontend
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: SonarCloud Analysis
        uses: sonarsource/sonarcloud-github-action@master
        with:
          project-key: parodontitis-web
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_WEB }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
